/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/accounts': RouteRecordInfo<'/accounts', '/accounts', Record<never, never>, Record<never, never>>,
    '/classes/': RouteRecordInfo<'/classes/', '/classes', Record<never, never>, Record<never, never>>,
    '/classes/[klass_id]/': RouteRecordInfo<'/classes/[klass_id]/', '/classes/:klass_id', { klass_id: ParamValue<true> }, { klass_id: ParamValue<false> }>,
    '/HelloWorld': RouteRecordInfo<'/HelloWorld', '/HelloWorld', Record<never, never>, Record<never, never>>,
    '/rules/[klass_id]/[category_id]/[rule_id]': RouteRecordInfo<'/rules/[klass_id]/[category_id]/[rule_id]', '/rules/:klass_id/:category_id/:rule_id', { klass_id: ParamValue<true>, category_id: ParamValue<true>, rule_id: ParamValue<true> }, { klass_id: ParamValue<false>, category_id: ParamValue<false>, rule_id: ParamValue<false> }>,
    '/summary': RouteRecordInfo<'/summary', '/summary', Record<never, never>, Record<never, never>>,
  }
}
